name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container: kcov/kcov
    steps:
      - name: "Install dependencies"
        run: |
          apt-get update && apt-get install -y --fix-missing git parallel curl
          useradd test

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Test"
        run: |
          chown -R test $(pwd)
          su - test bash -c $(pwd)/scripts/test.sh

      - name: "Coveralls"
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: "cobertura"
          files: "coverage/bats/cobertura.xml"
